### ISSUE TITLE
关于使用方法里的命令用什么运行？

### ISSUE THREAD

**Issue by yicx** [ctguggbond/ZhihuDTW#2]
![123](https://user-images.githubusercontent.com/38092527/38534643-b1872f92-3cb1-11e8-9d56-13f180683752.jpg)
上图红色框中的命令要用什么来运行？我尝试过用windows的cmd打开来执行命令不行。

**Comment by ggbond2077** [comment]
需要安装git. 没有git .你可以选择下载zip包
